<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\logo256.ico</ApplicationIcon>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <EnableTrimAnalyzer>true</EnableTrimAnalyzer>
    <IsTrimmable>true</IsTrimmable>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <TrimmerRootAssembly Include="Silk.NET.Assimp" />
    <TrimmerRootAssembly Include="Silk.NET.OpenGL" />
    <TrimmerRootAssembly Include="Semi.Avalonia" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.999-cibuild0065577-alpha" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.999-cibuild0065577-alpha" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.999-cibuild0065577-alpha" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.999-cibuild0065577-alpha" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.1">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Semi.Avalonia" Version="12.0.3" />
    <PackageReference Include="Silk.NET.Assimp" Version="2.23.0" />
    <PackageReference Include="Silk.NET.OpenGL" Version="2.23.0" />
  </ItemGroup>
</Project>
