using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using System.Text.Json;

namespace ModelDownloader.Services;

/// <summary>
/// 将标准格式文档转换为 PADS ASCII 库(.asc,Altium 导入向导支持导入)。
/// 注意:PADS ASCII 无官方公开规范,本实现按社区常见样例结构生成,属实验性质。
/// 单位:PADS 库使用 1/100 mil(即 mil × 100)。
/// </summary>
public static class PadsConverter
{
    private const double ToPads = 100.0; // mil → 1/100 mil

    /// <summary>封装文档 → *LAN* 段。</summary>
    public static string ConvertFootprint(string oldDoc, string name, string? designator)
    {
        var sb = new StringBuilder(8 * 1024);
        sb.Append("*PADS-LIBRARY-ASCII-V2020.0*\n\n*PART*\n\n*LAN*\n");
        sb.Append(name).Append("  ").Append(name).Append('\n');
        sb.Append("*REMARK* Generated by lcsc_model_downloader\n");

        foreach (var a in Parse(oldDoc))
        {
            switch (S(a[0]))
            {
                case "PAD":
                {
                    var number = S(a[5]);
                    var x = N(a[6]) * ToPads;
                    var y = N(a[7]) * ToPads;
                    var shape = a[10];
                    var w = shape.GetArrayLength() > 1 ? Math.Abs(N(shape[1])) * ToPads : 0;
                    var h = shape.GetArrayLength() > 2 ? Math.Abs(N(shape[2])) * ToPads : 0;
                    sb.Append("P ").Append(number).Append(" 0 0 0  ")
                      .Append(F(x)).Append(' ').Append(F(y)).Append("  0  ")
                      .Append(F(w)).Append(' ').Append(F(h)).Append('\n');
                    break;
                }

                case "POLY":
                {
                    var width = Math.Max(N(a[5]) * ToPads, 1);
                    var pts = a[6];
                    if (pts.ValueKind != JsonValueKind.Array || pts.GetArrayLength() < 4) break;
                    var px = new List<double>();
                    var py = new List<double>();
                    for (var i = 0; i + 1 < pts.GetArrayLength(); i++)
                    {
                        if (pts[i].ValueKind == JsonValueKind.Number)
                        {
                            px.Add(N(pts[i]) * ToPads);
                            py.Add(N(pts[i + 1]) * ToPads);
                            i++;
                        }
                    }
                    for (var i = 0; i + 1 < px.Count; i++)
                    {
                        sb.Append("L 0 0 0  ")
                          .Append(F(px[i])).Append(' ').Append(F(py[i])).Append("  ")
                          .Append(F(px[i + 1])).Append(' ').Append(F(py[i + 1])).Append("  ")
                          .Append(F(width)).Append('\n');
                    }
                    break;
                }

                case "ATTR":
                {
                    // Designator 文本行
                    if (S(a[7]) == "Designator")
                    {
                        sb.Append("T 1 0 0  0 0  60 0 0 0 ")
                          .Append(Esc(S(a[8]))).Append('\n');
                    }
                    break;
                }
            }
        }

        return sb.ToString();
    }

    /// <summary>符号文档 → *PART* 段(实验性)。</summary>
    public static string ConvertSymbol(string oldDoc, string name, string? designator)
    {
        var sb = new StringBuilder(8 * 1024);
        sb.Append("*PADS-LIBRARY-ASCII-V2020.0*\n\n*LAN*\n\n*PART*\n");
        sb.Append(name).Append("  ").Append(name).Append('\n');
        sb.Append("*REMARK* Generated by lcsc_model_downloader (experimental)\n");

        foreach (var a in Parse(oldDoc))
        {
            if (S(a[0]) != "PIN") continue;
            var number = S(a[1]);
            var x = N(a[4]) * ToPads;
            var y = -N(a[5]) * ToPads;
            sb.Append("PIN ").Append(number).Append("  0  ")
              .Append(F(x)).Append(' ').Append(F(y)).Append('\n');
        }

        return sb.ToString();
    }

    private static IEnumerable<JsonElement> Parse(string oldDoc)
    {
        foreach (var raw in oldDoc.Split('\n'))
        {
            var line = raw.Trim();
            if (line.Length == 0 || !line.StartsWith('[')) continue;
            JsonElement? element = null;
            try
            {
                using var doc = JsonDocument.Parse(line);
                if (doc.RootElement.ValueKind == JsonValueKind.Array && doc.RootElement.GetArrayLength() > 0)
                    element = doc.RootElement.Clone();
            }
            catch (JsonException)
            {
            }
            if (element != null) yield return element.Value;
        }
    }

    private static string F(double v) => ((long)Math.Round(v)).ToString(CultureInfo.InvariantCulture);

    private static string Esc(string? s) => "\"" + (s ?? string.Empty).Replace("\"", "'") + "\"";

    private static string S(JsonElement e)
        => e.ValueKind == JsonValueKind.String ? e.GetString() ?? string.Empty : e.GetRawText();

    private static double N(JsonElement e)
        => e.ValueKind == JsonValueKind.Number ? e.GetDouble() : 0;
}
